export const LISTA_CONVERSAS_OK = 'LISTA_CONVERSAS_OK'
export const LISTA_CONVERSAS_ERROR = 'LISTA_CONVERSAS_ERROR'

export const LISTA_MENSAGENS_OK = 'LISTA_MENSAGENS_OK'
export const LISTA_MENSAGENS_ERROR = 'LISTA_MENSAGENS_ERROR'
